### ISSUE TITLE
[BUG]  le**-high instructions fail in bpf_conformance test

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/llvmbpf#17]
**Describe the bug**

The bpf_conformance has error with:

```
Test "./bpf_conformance/tests/le16-high.data" failed: Plugin returned incorrect return value 13532434998891647266 expected 4386
Test "./bpf_conformance/tests/le16.data" succeeded
Test "./bpf_conformance/tests/le32-high.data" failed: Plugin returned incorrect return value 15991999702591746884 expected 287454020
```

**Comment by Officeyutong** [comment]
It's a bug, we haven't handle truncate for little endian conversions. Though byte orders doesn't need to be changed, but truncation is necessary for `le16`, `le32`

At https://github.com/eunomia-bpf/llvmbpf/blob/d95c50e3c2b8f91143172f6dc200bb8276eb90fa/src/compiler_utils.cpp#L104

**Comment by yunwei37** [comment]
Great!
